name: scriblet
description: "A Drawing and Guessing Game"
publish_to: "none"
version: 1.5.0+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  socket_io_client: 3.1.2
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/pencil.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: BeachDay
      fonts:
        - asset: assets/fonts/beachday.ttf
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
    - family: Ezydraw
      fonts:
        - asset: assets/fonts/Ezydraw.ttf
